ELS PREUS S'ACTUALITZEN AUTOMATICAMENT DES DEL CHEF
<br/>
<br/>
<br/>
SUGGERIMENTS, PREU MIG I ACTIVAR MENU CALÇOTS ES FA DES DE LA <a href="../taules/DBTable/FormConfigAdmin.php">COFIGURACIÓ AVANÇADA</a>