<?php
$translate["SI NO REPS MAIL REVISA SPAM O CANTACTAN'S: restaurant@can-borrell.com"] 
    = "SI NO RECIBES MAIL REVISA SPAM O CANTACTANOS: restaurant@can-borrell.com";




$translate["LA RESERVA {ID} PER AL DIA {DIA} ESTA CONFIRMADA.HEM ENVIAT MAIL AMB INTRUCCIONS PER AL PAGAMENT."] 
    = "TU RESERVA {ID} PARA EL DIA {DIA} ESTA CONFIRMADA.HEMOS ENVIADO MAIL CON INTRUCCIONES PARA EL PAGO.";

$translate["LA RESERVA {ID} PER AL DIA {DIA} HA ESTAT DENEGADA.HEM ENVIAT MAIL AMB MES DETALLS."] 
    = "TU RESERVA {ID} PARA EL DIA {DIA} HA SIDO DENEGADA. TE HEMOS ENVIADO EMAIL CON MAS DETALLES.";



$translate["HEM REBUT CONFIRMACIO DEL PAGAMENT DE LA TEVA RESERVA {ID} PER AL DIA {DIA}. TE ESPERAMOS EN CAN-BORRELL"] 
    = "HEMOS RECIBIDO CONFIRMACION DEL PAGO DE TU RESERVA {ID} PARA EL DIA {DIA}. TE ESPERAMOS EN CAN-BORRELL";

$translate[""] 
    = "";

$translate[""] 
    = "";



